# Generated by Django 5.0.1 on 2025-03-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveScanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, null=True)),
                ('query', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Active Scanner',
                'verbose_name_plural': 'Active Scanners',
                'db_table': 'active_scanners',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('filterID', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_idx', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('url', models.TextField(null=True)),
                ('img', models.TextField(null=True)),
                ('query', models.CharField(max_length=50, null=True)),
                ('search_title', models.TextField(null=True)),
                ('watchlist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
