# Generated by Django 5.0.1 on 2025-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescanner',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='status',
            field=models.CharField(default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='town',
            field=models.CharField(max_length=100),
        ),
    ]
