# Generated by Django 5.0.1 on 2025-03-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activescanner_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('marketplace_url_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
        migrations.RemoveField(
            model_name='activescanner',
            name='town',
        ),
        migrations.AddField(
            model_name='listing',
            name='scanner_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='search_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ScannerLocationMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activescanner')),
            ],
            options={
                'verbose_name': 'Scanner Location Mapping',
                'verbose_name_plural': 'Scanner Location Mappings',
                'db_table': 'scanner_location_mappings',
                'unique_together': {('scanner', 'location')},
            },
        ),
        migrations.AddField(
            model_name='activescanner',
            name='locations',
            field=models.ManyToManyField(related_name='scanners', through='main.ScannerLocationMapping', to='main.location'),
        ),
    ]
