# Generated by Django 5.0.1 on 2025-03-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location_remove_activescanner_town_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='search_location',
            new_name='search_locations',
        ),
    ]
